### ISSUE TITLE
methods in confusion matrix

### ISSUE THREAD

**Issue by hyunjong** [geekfeiw/Multi-Scale-1D-ResNet#1]
Hey Fei. Thanks for sharing the nice works and the results.
I like your network as it is very powerful and efficient. 
BTW, can you please specify the methods in the confusion matrix like M-RL CNN?
I looked over the CSI-net paper to figure it out, but nothing found.

**Comment by geekfeiw** [comment]
@hyunjong We thank you like this code. M-RL CNN is the name of the networks shown in the first figure. Others are ablation study, using kernel in one specific scales, such as 1x3, 1x5, 1x7. You could find corresponding codes at the **model** .
